<br/>
<br/>
<?php
 $title = 'Add new album';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php
 $form->setAttribute('action', $this->url('events', array('action' => 'add')));
 $form->prepare();

 echo $this->form()->openTag($form)."<br>";
 echo $this->formHidden($form->get('id'))."<br>";
 echo $this->formRow($form->get('title'))."<br>";
 echo $this->formRow($form->get('event_type'))."<br>";
 echo $this->formSubmit($form->get('submit'))."<br>";
 echo $this->form()->closeTag();