<br/>
<br/>
<?php
 // module/Album/view/album/album/edit.phtml:

 $title = 'Edit Event';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <?php
 $form = $this->form;
 $form->setAttribute('action', $this->url(
     'events',
     array(
         'action' => 'edit',
         'id'     => $this->id,
     )
 ));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'))."<br>";
 echo $this->formRow($form->get('title'))."<br>";
 echo $this->formRow($form->get('event_type'))."<br>";
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();